### ISSUE TITLE
Failed try event which is called after every failed try

### ISSUE THREAD

**Issue by cyril265** [rholder/guava-retrying#19]
It would be useful to be able to log failed tries.

```
FailedTryHandler handler = new FailedTryHandler() {
      public void handle(FailedTryEvent event) {
           logger.warn("Failed to do stuff, retrying", event.getException()); //or event.getResult()
      }
};

Retryer<Boolean> retryer = RetryerBuilder.<Boolean>newBuilder()
        .retryIfException()
        .withStopStrategy(...)
        .withFailedTryHandler(handler)
        .build();
```

**Comment by JohnnyMarnell** [comment]
@rholder hey, great lib -- I see the generic `RetryListener` that went into the 2.0.0 release, but I really want to be able to log / do stuff *only* in the failure case option as well, as above.  (To do this with the generic `RetryListener`, I have to be aware of the exact predicates that were used to build the re-tryer, and re-check them, thus tedious and wasteful).  I see there hasn't been a release in a while, if I made a PR would you consider? Thanks!
