### ISSUE TITLE
Be consistent about "duration" method parameters 

### ISSUE THREAD

**Issue by Stephan202** [rholder/guava-retrying#30]
The `AttemptTimeLimiters` and `WaitStrategies` classes have methods that take a `(long, TimeUnit)` pair, whereas `StopStrategies#stopAfterDelay` accepts only a `long`. Not a big deal, but slightly unfortunate from an API point of view.

How about aligning `StopStrategies` with the other two classes by introducing `StopStrategies#stopAfterDelay(long, TimeUnit)` and deprecating `StopStrategies#stopAfterDelay(long)`?

(I understand the some of the strategy interfaces also take only a `long`, but most users will not implement those themselves, and in any case those types are in some sense more "low level".)

**Comment by rholder** [comment]
I like consistency, too. That's a good catch. Feel free to open a PR for it, and I'll get it into the next release.

**Comment by Stephan202** [comment]
Cool. I opened PR #39.

**Comment by rholder** [comment]
Your duration method parameter consistency fix should be good to go now in 2.0.0. Thanks again for your contributions.
