### ISSUE TITLE
Releasing 1.0.7 to maven central?

### ISSUE THREAD

**Issue by nwillc** [rholder/guava-retrying#31]
There are some changes in the repo that I'd like to use in a project.  Any chance of a 1.0.7 release to maven central?

**Comment by rholder** [comment]
Sure, I have a pile of things to do on this project that I've had sitting around for a while. I can cut a 1.0.7 release with what's out there in master right now since it should be backward compatible.

**Comment by nwillc** [comment]
Awesome, many thanks!


On Jan 20, 2015, at 23:43, Ray Holder <notifications@github.com> wrote:

Sure, I have a pile of things to do on this project that I've had sitting
around for a while. I can cut a 1.0.7 release with what's out there in
master right now since it should be backward compatible.

—
Reply to this email directly or view it on GitHub
<https://github.com/rholder/guava-retrying/issues/31#issuecomment-70783716>.

**Comment by rholder** [comment]
1.0.7 should be up there now.

**Comment by nwillc** [comment]
Many thanks!


On Jan 21, 2015, at 19:03, Ray Holder <notifications@github.com> wrote:

1.0.7 should be up there now.

—
Reply to this email directly or view it on GitHub
<https://github.com/rholder/guava-retrying/issues/31#issuecomment-70947428>.
