### ISSUE TITLE
Remove use of Maven dependency ranges for Guava dependency

### ISSUE THREAD

**Issue by voiceinsideyou** [rholder/guava-retrying#32]
Minor quibble here - but would it be possible to avoid using the fixed dependency range of `[10.0+,15.0]` for Guava in the guava-retrying POM?

It kind-of forces people to use an exclude on this transitive dependency in order to use updated guava versons in their own code because the end of the range in the POM is currently fixed at v15.0. On the general assumption that the guava team don't make API-breaking changes; I think it's a reasonable assumption that guava-retrying will work on forthcoming Guava releases (we're now up to 18.0 and we're still using guava-retrying without issue) so is making this dependency open-ended such as `[10.0+,)` an option?

**Comment by Stephan202** [comment]
I suggest just specifying a single Guava version. Dependants (i.e., downstream users) can always override the selected version. (And generally will, because they'll use Guava for other things as well, and so will have (or at least *should* have) declared Guava as an explicit dependency anyway).

**Comment by yaronr** [comment]
+1

**Comment by voiceinsideyou** [comment]
Yeah, I'd also generally prefer a single version - was just looking for a middle ground as some people love ranges :)

**Comment by rferreira** [comment]
+1 on this

**Comment by rholder** [comment]
Sure, I can make this an open range in the next release.

**Comment by rholder** [comment]
It's now an open range in the 2.0.0 release.

**Comment by voiceinsideyou** [comment]
Thanks!
