### ISSUE TITLE
use com.google.code.findbugs:annotations instead of com.google.code.findbugs:jsr305

### ISSUE THREAD

**Issue by ryandm** [rholder/guava-retrying#33]
As noted at https://github.com/facebook/facebook-oss-pom/blob/master/pom.xml#L331-L336, bad things happen when :annotations and :jsr305 are both incorporated into the same project.

How do you feel about switching to :annotations to make it less dependency-error-prone to incorporate com.github.rholder:guava-retrying into a project?

**Comment by Stephan202** [comment]
I understand that `:annotations` is a superset of `:jsr305`, but one could just as well make the argument in the opposite direction. Our projects only use `:jsr305`, so this change would not be beneficial for us.

Note that the dependency checker can be "helped" in two ways:

1. By excluding the unwanted upstream dependency. (This is the approach `facebook-oss-pom` takes.)
2. By reordering dependencies. (Thereby effectively reordering the classpath.)

Alternative suggestion: have `guava-retrying` declare the `:jsr305` dependency as `provided`. We do this in our projects. This way dowstream dependencies can freely select between `:annotations` and `:jsr305`, or even omit both ([source](https://stackoverflow.com/questions/3567413/why-doesnt-a-missing-annotation-cause-a-classnotfoundexception-at-runtime)).

**Comment by KostyaSha** [comment]
Looks like a wrong runtime dependency https://github.com/rholder/guava-retrying/blob/master/build.gradle#L85

**Comment by ryandm** [comment]
(Closing as wontfix)
