### ISSUE TITLE
Reuse Retryer across threads

### ISSUE THREAD

**Issue by dominicfarr** [rholder/guava-retrying#35]
Are the Retryer's thread safe? 

For example, I would like to use a single retry strategy across my web application. I built the Retryer once, and reuse it in any classes that requires a retrying call?

**Comment by rholder** [comment]
Yes, they should all be thread-safe. Here's an example of one that could be shared:
```java
private static final Retryer<APIResponse> API_RETRYER = RetryerBuilder.<APIResponse>newBuilder()
        .retryIfException()
        .withWaitStrategy(WaitStrategies.fixedWait(500, TimeUnit.MILLISECONDS))
        .withStopStrategy(StopStrategies.stopAfterAttempt(2))
        .build();
```
