### ISSUE TITLE
is there a way to make it log what it's doing? 

### ISSUE THREAD

**Issue by nddipiazza** [rholder/guava-retrying#71]
i like the library. but i need a log message in my use case when a retry was 1) needed and 2) what count it is

can it be done?

**Comment by JensRantil** [comment]
Yes, you can register a retry listener.

**Comment by smartvolshell** [comment]
or implements yourself strategies

**Comment by nddipiazza** [comment]
yep that's what i did. used a retry listener and it was quite simple. just note to make sure don't log when attempt number = 1 because that will get very noisy
